openapi: 3.0.0
info:
  title: 모두의 총무
  description: 모두의 총무 API Docs
  version: 0.0.1
  contact:
    name: API support
    url: gyrms9412@naver.com
    email: gyrms9412@naver.com
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
servers:
  - url: 'https://[api-gateway-id].execute-api.ap-northeast-2.amazonaws.com/stag'
    description: Stag server
paths:
  # test
  /test:
    get:
      summary: test
      description: 테스트 함수
      operationId: test/get
      tags:
        - test
      parameters:
        - name: name
          in: query
          description: test parameter 1
          required: true
          schema:
            type: string
        - name: age
          in: query
          description: test parameter 2
          required: true
          schema:
            type: integer
        - name: favoriteFood
          in: query
          description: test parameter 3
          schema:
            enum:
              - pizza
              - taco
              - fries
      responses:
        '200':
          description: test success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      name:
                        type: string
                        description: test output 1
                      age:
                        type: integer
                        description: test output 2
        '500':
          description: 'code: Internal_Server_Error'
  
  # User
  /user:
    get:
      summary: user
      description: User 정보를 조회한다. (token 정보로 DB 조회)
      operationId: user/get
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: |
            유저 데이터 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'

    put:
      summary: user
      description: |
        - userName이 없는 유저에게 userName을 부여하고 회원가입 처리를 완료한다.
        - User 정보를 수정한다.
      operationId: user/put
      tags:
        - user
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: 유저 이름 수정 요청시
                marketingAgreed:
                  type: boolean
                  description: 마케팅 동의 여부 수정 요청시
                statusMessage:
                  type: string
                  description: 상태 메시지 수정 요청시
      responses:
        '200':
          description: 수정된 유저 데이터 전달
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                      
    delete:
      summary: user
      description: accessToken의 claim을 참조해 User를 삭제한다.
      operationId: user/delete
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  userEmail:
                    type: string
                    description: 삭제된 유저의 이메일

  # Signin
  /signin/apple:
    post:
      summary: signin
      description: |
        - Apple 회원가입 / 로그인
        - 회원가입 시 response의 processType: signup
          이후 PUT user API로 userName을 부여해야 회원가입 완료
        - 로그인 시 response의 processType: signin
      operationId: signin/apple/post
      tags:
        - signin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Apple에서 발급한 identityToken
      responses:
        '200':
          description: 회원가입 / 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  processType:
                    type: string
                    description: signup or signin
                  accessToken:
                    type: string
                    description: 로그인 성공 시 발급되는 accessToken
                  refreshToken:
                    type: string
                    description: 로그인 성공 시 발급되는 refreshToken
        '401':
          description: 'code: Verification_Failed'
        '500':
          description: 'code: Internal_Server_Error'
  
  /signin/google:
    post:
      summary: signin
      description: |
        - Google 회원가입 / 로그인
        - 회원가입 시 response의 processType: signup
          이후 PUT user API로 userName을 부여해야 회원가입 완료
        - 로그인 시 response의 processType: signin
      operationId: signin/google/post
      tags:
        - signin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Google에서 발급한 id Token
      responses:
        '200':
          description: 회원가입 / 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  processType:
                    type: string
                    description: signup or signin
                  accessToken:
                    type: string
                    description: 로그인 성공 시 발급되는 accessToken
                  refreshToken:
                    type: string
                    description: 로그인 성공 시 발급되는 refreshToken
        '401':
          description: 'code: Verification_Failed'
        '500':
          description: 'code: Internal_Server_Error'

  /signin/kakao:
    post:
      summary: signin
      description: |
        - Kakao 회원가입 / 로그인
        - 회원가입 시 response의 processType: signup
          이후 PUT user API로 userName을 부여해야 회원가입 완료
        - 로그인 시 response의 processType: signin
      operationId: signin/kakao/post
      tags:
        - signin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Kakao에서 발급한 access token
      responses:
        '200':
          description: 회원가입 / 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  processType:
                    type: string
                    description: signup or signin
                  accessToken:
                    type: string
                    description: 로그인 성공 시 발급되는 accessToken
                  refreshToken:
                    type: string
                    description: 로그인 성공 시 발급되는 refreshToken
        '401':
          description: 'code: Verification_Failed'
        '500':
          description: 'code: Internal_Server_Error'
  
  /signin/naver:
    post:
      summary: signin
      description: |
        - Naver 회원가입 / 로그인
        - 회원가입 시 response의 processType: signup
          이후 PUT user API로 userName을 부여해야 회원가입 완료
        - 로그인 시 response의 processType: signin
      operationId: signin/naver/post
      tags:
        - signin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Naver에서 발급한 access token
      responses:
        '200':
          description: 회원가입 / 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  processType:
                    type: string
                    description: signup or signin
                  accessToken:
                    type: string
                    description: 로그인 성공 시 발급되는 accessToken
                  refreshToken:
                    type: string
                    description: 로그인 성공 시 발급되는 refreshToken
        '401':
          description: 'code: Verification_Failed'
        '500':
          description: 'code: Internal_Server_Error'
  
  # Friend
  /friend:
    post:
      summary: friend
      description: |
        - 내 친구목록에 새로운 친구 추가하고 추가된 친구에게 푸시 알림 전송
        - 이미 추가된 친구인 경우 response의 isAlreadyFriend: true로 응답
      operationId: friend/post
      tags:
        - friend
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newFriendName:
                  type: string
                  description: 추가할 친구의 이름
      responses:
        '200':
          description: 친구 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  newFriendName:
                    type: string
        '500':
          description: 'code: Internal_Server_Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        userEmail:
          type: string
        userName:
          type: string
        registerType:
          type: string
        registeredDate:
          type: string
        lastLoginDate:
          type: string
        marketingAgreed:
          type: number
        